### ISSUE TITLE
Print ExperimentData

### ISSUE THREAD

**Issue by maxkukkola** [bessagroup/f3dasm#229] opened 2023-11-09 19:41 UTC
It would be nice to have a feature that lets you print the ExperimentData when running code from your IDE or terminal (similar to how you have shown it can do in Jupyter notebooks). 

![Selection_039](https://github.com/bessagroup/f3dasm/assets/62596766/b0aad484-ca69-4535-a006-dbd0e3896719)

For example when you print(data) it can display it or alternatively a method similar to pandas.DataFrame.head could be useful where only the first n values are shown. This would help a lot with debugging and for beginners to learn.

**Comment by mpvanderschelling** [comment] 2023-11-09 19:53
Duplicate of #227

**Closed** 2023-11-09 19:53 UTC
